// const form header
const hintSearch = document.querySelector("#hint");
const mainHeaderSearch = document.querySelector(".main-header-search");
const searchInputHeader = document.querySelector(".main-header-search-input");
const btnCloseSearch = document.querySelector("#btn-close-search");
// const form menu
const menu = document.querySelector(".menu");
const menuBtn = document.querySelector(".btn-menu");
const menuPages = document.querySelector("#menu-pages");
const btnMenuPages = document.querySelectorAll(".btn-menu-pages");
const textBtn = document.querySelectorAll(".text-btn");
// const from field
const fields = document.querySelectorAll(".field");
